spring:
  application:
    name: auth-server
  profiles:
    active:  docker

server:
  port: 9080
  contextPath: /tr

logging:
  level:
    org.springframework.security: DEBUG
    
com:
  traderocker:
    authserver:
      config:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost
        port: 3306
        databaseName: oauth_db
        userName: root
        password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
        
include:
  test:
    users: true
  db:
    users: true
  ldap:
    users: true
        
ldap:
  ldapUrl: ldap://127.0.0.1:10389/dc=example,dc=com
  bindPW: 
  groupSearchBase: dc=groups
	groupSearchFilter: (uniqueMember={0})
	userDnPattern: uid={0},dc=people

---

spring:
  profiles: docker

com:
  traderocker:
    authserver:
      config:
        password: password
        
---

spring:
  profiles: local
  
com:
  traderocker:
    authserver:
      config:
        password: password
